from typing import Any

class QObject: ...
class QWidget(QObject): ...
class QApplication(QObject): ...
class QDialog(QWidget): ...
class QMessageBox(QWidget): ...
class QVBoxLayout(QObject): ...
class QTextEdit(QWidget): ...
class QLineEdit(QWidget): ...
class QPushButton(QWidget): ...
class QAction(QObject): ...
class QLabel(QWidget): ...